export const seedJobs = [
  {
    title: "Kỹ Thuật Viên Bảo Trì Hạ Tầng Viễn thông",
    location: "Tiền Giang",
    deadline: "31/07/2026",
    salary: "8 - 15 triệu ₫",
    href: "https://fptjobs.com/ky-thuat-vien-bao-tri-ha-tang-vien-thong-25801",
    department: "Kỹ thuật",
    employmentType: "Toàn thời gian",
    level: "Nhân viên",
    description:
      "Triển khai, bảo trì và xử lý sự cố hạ tầng viễn thông cho khách hàng tại địa bàn được phân công.",
    requirements: [
      "Tốt nghiệp trung cấp trở lên các ngành kỹ thuật, điện tử, viễn thông hoặc công nghệ thông tin.",
      "Có sức khỏe tốt, chủ động di chuyển và sẵn sàng hỗ trợ khách hàng.",
      "Tinh thần trách nhiệm cao, giao tiếp lịch sự và tuân thủ quy trình kỹ thuật.",
    ],
    benefits: [
      "Thu nhập cạnh tranh theo năng lực và hiệu quả công việc.",
      "Được đào tạo nghiệp vụ, kỹ năng và quy trình triển khai thực tế.",
      "Chế độ bảo hiểm, phúc lợi và lộ trình phát triển rõ ràng.",
    ],
  },
  {
    title: "Nhân viên Kinh doanh (Cầu Giấy)",
    location: "Hà Nội",
    deadline: "31/07/2026",
    salary: "8 - 20 triệu ₫",
    href: "https://fptjobs.com/nhan-vien-kinh-doanh-cau-giay-25874",
    hot: true,
    department: "Kinh doanh",
    employmentType: "Toàn thời gian",
    level: "Nhân viên",
    description:
      "Tìm kiếm, tư vấn và phát triển khách hàng sử dụng dịch vụ viễn thông, truyền hình và các sản phẩm số của FPT Telecom.",
    requirements: [
      "Yêu thích kinh doanh, có kỹ năng giao tiếp và thuyết phục tốt.",
      "Chủ động mở rộng tệp khách hàng tại khu vực phụ trách.",
      "Có tinh thần học hỏi, chịu được áp lực doanh số và mục tiêu tháng.",
    ],
    benefits: [
      "Lương cứng, hoa hồng và thưởng kinh doanh theo kết quả.",
      "Đào tạo sản phẩm, kỹ năng bán hàng và kỹ năng chăm sóc khách hàng.",
      "Cơ hội thăng tiến lên các vị trí quản lý kinh doanh.",
    ],
  },
  {
    title: "Nhân viên kỹ thuật triển khai và bảo trì mạng viễn thông (Hà Nội)",
    location: "Hà Nội",
    deadline: "31/07/2026",
    salary: "10 - 15 triệu ₫",
    href: "https://fptjobs.com/nhan-vien-ky-thuat-trien-khai-va-bao-tri-mang-vien-thong-ha-noi-25865",
    hot: true,
    department: "Kỹ thuật",
    employmentType: "Toàn thời gian",
    level: "Nhân viên",
    description:
      "Lắp đặt, cấu hình và bảo trì đường truyền internet, truyền hình và thiết bị đầu cuối cho khách hàng.",
    requirements: [
      "Có kiến thức cơ bản về mạng máy tính, viễn thông hoặc điện dân dụng.",
      "Có khả năng làm việc ngoài hiện trường và xử lý tình huống nhanh.",
      "Ưu tiên ứng viên có kinh nghiệm triển khai hạ tầng mạng.",
    ],
    benefits: [
      "Thu nhập ổn định, phụ cấp theo chính sách và thưởng hiệu quả.",
      "Được cấp công cụ, đồng phục và đào tạo nghiệp vụ.",
      "Môi trường kỹ thuật trẻ, thực chiến và nhiều cơ hội học hỏi.",
    ],
  },
  {
    title: "Nhân viên Kinh doanh dịch vụ Viễn thông (Quận 7 , Nhà Bè)",
    location: "Hồ Chí Minh",
    deadline: "31/07/2026",
    salary: "Lương thỏa thuận",
    href: "https://fptjobs.com/nhan-vien-kinh-doanh-dich-vu-vien-thong-quan-7--nha-be-25870",
    department: "Kinh doanh",
    employmentType: "Toàn thời gian",
    level: "Nhân viên",
    description:
      "Phát triển khách hàng cá nhân và hộ gia đình tại khu vực Quận 7, Nhà Bè cho các dịch vụ viễn thông của FPT Telecom.",
    requirements: [
      "Nhanh nhẹn, giao tiếp tốt và yêu thích công việc thị trường.",
      "Có khả năng lập kế hoạch tiếp cận khách hàng theo địa bàn.",
      "Không yêu cầu kinh nghiệm, được đào tạo từ đầu.",
    ],
    benefits: [
      "Thu nhập theo năng lực, hoa hồng không giới hạn.",
      "Được hỗ trợ đào tạo sản phẩm và kỹ năng bán hàng.",
      "Làm việc gần khu vực phụ trách, đội nhóm hỗ trợ sát sao.",
    ],
  },
  {
    title: "Nhân viên Dịch vụ khách hàng (Quận 7)",
    location: "Hồ Chí Minh",
    deadline: "31/07/2026",
    salary: "8 - 13 triệu ₫",
    href: "https://fptjobs.com/nhan-vien-dich-vu-khach-hang-quan-7-25871",
    department: "Dịch vụ khách hàng",
    employmentType: "Toàn thời gian",
    level: "Nhân viên",
    description:
      "Tiếp nhận, tư vấn và hỗ trợ khách hàng trong quá trình sử dụng dịch vụ của FPT Telecom.",
    requirements: [
      "Giọng nói rõ ràng, giao tiếp lịch sự và có tinh thần phục vụ.",
      "Biết xử lý tình huống, phối hợp với các bộ phận liên quan.",
      "Ưu tiên ứng viên có kinh nghiệm chăm sóc khách hàng.",
    ],
    benefits: [
      "Thu nhập ổn định và chế độ phúc lợi đầy đủ.",
      "Được đào tạo nghiệp vụ dịch vụ khách hàng.",
      "Môi trường làm việc chuyên nghiệp, có lộ trình phát triển.",
    ],
  },
  {
    title: "Kỹ Sư Vận Hành Hệ Thống CNTT (IT Operation System Engineer)",
    location: "Hồ Chí Minh",
    deadline: "08/08/2026",
    salary: "13 - 15 triệu ₫",
    href: "https://fptjobs.com/ky-su-van-hanh-he-thong-cntt-it-operation-system-engineer-25872",
    department: "Công nghệ thông tin",
    employmentType: "Toàn thời gian",
    level: "Nhân viên",
    description:
      "Theo dõi, vận hành và xử lý sự cố hệ thống CNTT, đảm bảo dịch vụ hoạt động ổn định.",
    requirements: [
      "Có kiến thức về hệ điều hành, mạng, monitoring và vận hành hệ thống.",
      "Có khả năng trực ca, phân tích log và xử lý sự cố theo quy trình.",
      "Ưu tiên ứng viên có kinh nghiệm Linux, cloud hoặc automation.",
    ],
    benefits: [
      "Được tiếp cận hệ thống quy mô lớn và quy trình vận hành chuyên nghiệp.",
      "Chính sách đào tạo, bảo hiểm và phúc lợi theo quy định.",
      "Cơ hội phát triển theo hướng system, DevOps hoặc service operation.",
    ],
  },
  {
    title: "Nhân viên Quản lý Vận hành sàn Thương mại điện tử (Ecommerce Planner)",
    location: "Hà Nội",
    deadline: "07/08/2026",
    salary: "Lương thỏa thuận",
    href: "https://fptjobs.com/nhan-vien-quan-ly-van-hanh-san-thuong-mai-ien-tu-ecommerce-planner-25851",
    hot: true,
    department: "Vận hành",
    employmentType: "Toàn thời gian",
    level: "Nhân viên",
    description:
      "Lập kế hoạch, theo dõi và tối ưu hoạt động vận hành trên các kênh thương mại điện tử.",
    requirements: [
      "Có tư duy dữ liệu, khả năng phối hợp đa bộ phận và quản lý tiến độ.",
      "Hiểu vận hành sàn thương mại điện tử, chương trình khuyến mại và chỉ số bán hàng.",
      "Cẩn thận, chủ động và có khả năng xử lý vấn đề nhanh.",
    ],
    benefits: [
      "Lương thỏa thuận theo năng lực.",
      "Cơ hội làm việc với các sản phẩm số và mô hình bán hàng đa kênh.",
      "Môi trường trẻ, nhiều dữ liệu thực tế để phát triển chuyên môn.",
    ],
  },
  {
    title: "Chuyên gia Phân tích Tài chính (Financial Analyst)",
    location: "Hà Nội",
    deadline: "31/07/2026",
    salary: "Lương thỏa thuận",
    href: "https://fptjobs.com/chuyen-gia-phan-tich-tai-chinh-financial-analyst-25852",
    hot: true,
    department: "Tài chính",
    employmentType: "Toàn thời gian",
    level: "Chuyên gia",
    description:
      "Phân tích số liệu tài chính, xây dựng báo cáo quản trị và hỗ trợ ra quyết định kinh doanh.",
    requirements: [
      "Có nền tảng tài chính, kế toán, kiểm toán hoặc phân tích dữ liệu.",
      "Thành thạo Excel, mô hình tài chính và tư duy phân tích.",
      "Ưu tiên ứng viên có kinh nghiệm tại doanh nghiệp quy mô lớn.",
    ],
    benefits: [
      "Lương thỏa thuận theo kinh nghiệm và năng lực.",
      "Làm việc với dữ liệu thực tế trong hệ sinh thái viễn thông lớn.",
      "Cơ hội tham gia các dự án tối ưu hiệu quả kinh doanh.",
    ],
  },
  {
    title: "Account Manager (Chinese & English Speaking)",
    location: "Hà Nội",
    deadline: "07/08/2026",
    salary: "Lương thỏa thuận",
    href: "https://fptjobs.com/account-manager-chinese--english-speaking-25853",
    hot: true,
    department: "Kinh doanh",
    employmentType: "Toàn thời gian",
    level: "Quản lý",
    description:
      "Quản lý khách hàng doanh nghiệp, duy trì quan hệ đối tác và phát triển cơ hội kinh doanh bằng tiếng Trung và tiếng Anh.",
    requirements: [
      "Sử dụng tốt tiếng Trung và tiếng Anh trong môi trường công việc.",
      "Có kinh nghiệm bán hàng B2B, quản lý khách hàng hoặc phát triển đối tác.",
      "Kỹ năng đàm phán, theo dõi hợp đồng và chăm sóc khách hàng tốt.",
    ],
    benefits: [
      "Thu nhập thỏa thuận, thưởng theo kết quả kinh doanh.",
      "Cơ hội làm việc với khách hàng và đối tác quốc tế.",
      "Lộ trình phát triển trong mảng kinh doanh doanh nghiệp.",
    ],
  },
  {
    title: "Chuyên viên Quản Lý Dự Án (Viễn thông)",
    location: "Hà Nội",
    deadline: "31/07/2026",
    salary: "18 - 25 triệu ₫",
    href: "https://fptjobs.com/chuyen-vien-quan-ly-du-an-vien-thong-25859",
    hot: true,
    department: "Dự án",
    employmentType: "Toàn thời gian",
    level: "Nhân viên",
    description:
      "Theo dõi tiến độ, điều phối nguồn lực và kiểm soát chất lượng các dự án viễn thông.",
    requirements: [
      "Có kinh nghiệm quản lý dự án, điều phối triển khai hoặc vận hành viễn thông.",
      "Biết lập kế hoạch, quản lý rủi ro và báo cáo tiến độ.",
      "Kỹ năng giao tiếp, phối hợp và xử lý vấn đề tốt.",
    ],
    benefits: [
      "Mức lương cạnh tranh theo năng lực.",
      "Được tham gia các dự án viễn thông thực tế trên quy mô lớn.",
      "Cơ hội phát triển kỹ năng quản trị dự án chuyên nghiệp.",
    ],
  },
  {
    title: "Nhân viên Nhân sự (Long An)",
    location: "Long An",
    deadline: "30/07/2026",
    salary: "10 - 15 triệu ₫",
    href: "https://fptjobs.com/nhan-vien-nhan-su-long-an-25846",
    hot: true,
    department: "Nhân sự",
    employmentType: "Toàn thời gian",
    level: "Nhân viên",
    description:
      "Thực hiện các nghiệp vụ nhân sự tại đơn vị, hỗ trợ tuyển dụng, hồ sơ lao động và hoạt động nội bộ.",
    requirements: [
      "Có kiến thức cơ bản về hành chính nhân sự và luật lao động.",
      "Cẩn thận, bảo mật thông tin và giao tiếp tốt.",
      "Ưu tiên ứng viên có kinh nghiệm tuyển dụng hoặc C&B.",
    ],
    benefits: [
      "Thu nhập ổn định và phúc lợi theo chính sách công ty.",
      "Môi trường nhân sự thực tế, gần hoạt động kinh doanh.",
      "Cơ hội phát triển chuyên môn trong hệ thống FPT Telecom.",
    ],
  },
  {
    title: "Chuyên viên Kiểm thử phần mềm (QC - Engineer)",
    location: "Hồ Chí Minh",
    deadline: "07/08/2026",
    salary: "Lương thỏa thuận",
    href: "https://fptjobs.com/chuyen-vien-kiem-thu-phan-mem-qc-engineer-25850",
    department: "Công nghệ thông tin",
    employmentType: "Toàn thời gian",
    level: "Nhân viên",
    description:
      "Thiết kế test case, kiểm thử chức năng và phối hợp với đội phát triển để đảm bảo chất lượng sản phẩm phần mềm.",
    requirements: [
      "Có kiến thức về quy trình kiểm thử, test case, bug report và release.",
      "Tư duy logic, cẩn thận và giao tiếp rõ ràng với đội phát triển.",
      "Ưu tiên ứng viên biết API testing, SQL hoặc automation testing.",
    ],
    benefits: [
      "Lương thỏa thuận theo năng lực.",
      "Được tham gia kiểm thử sản phẩm thực tế trong hệ sinh thái FPT Telecom.",
      "Cơ hội phát triển theo hướng QA, automation hoặc product quality.",
    ],
  },
];
